apiVersion: v1
kind: Service
metadata:
  name: hello-loadbalancer-service
spec:
  ports:
  - port: 80
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: hello-loadbalancer
  type: LoadBalancer