apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-controller
spec:
  replicas: 2
  selector:
    app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: k8s-demo
        image: rodrigoguedes/docker-demo:0.0.1
        ports:
        - name: nodejs-port
          containerPort: 3000