apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels: 
    app: mysql
    lab: kubernetes-lab    
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi